# Generated by Django 5.0 on 2024-01-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='genres',
            new_name='category',
        ),
    ]
