# Generated by Django 5.0 on 2024-01-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_genre_category_rename_genres_music_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
