# Generated by Django 5.0 on 2024-01-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_music_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='musicfile',
            new_name='file',
        ),
    ]
