# Generated by Django 5.0 on 2024-01-12 11:29

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_music_added_at_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(default=app.models.default_music_photo, upload_to='playlist_photos'),
        ),
    ]
