# Generated by Django 4.1.13 on 2024-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_playlist_slug_alter_playlist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
