# Generated by Django 4.2.5 on 2024-01-25 05:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='photo',
            field=models.ImageField(default=app.models.default_music_photo, upload_to='music_photos'),
        ),
    ]
