# Generated by Django 4.2.5 on 2023-09-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField()),
                ('released_time', models.DateTimeField()),
                ('upload_music_file', models.FileField(max_length=255, upload_to='uploads/% Y/% m/% d/')),
                ('album_email', models.EmailField(default=None, max_length=254)),
                ('song_duration', models.FloatField(default=0.0)),
                ('image_upload', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.musician')),
            ],
        ),
    ]
